import type { SkillInfo } from './types.js'

export function getQualityGateSkill(): SkillInfo {
  return {
    name: 'openflow-quality-gate',
    description: 'Quality Gate executed after code changes or bug fixes. AI should call openflow-quality-gate and not claim completion until readiness is returned.',
    content: [
      '# OpenFlow Quality Gate Skill',
      '',
      '## Overview',
      '',
      'The quality gate is an AI-callable verification that runs after implementation code changes or bug fixes.',
      'It is NOT a user slash command — it is invoked by the AI during implementation.',
      '',
      '## When to Invoke',
      '',
      'Invoke this skill AFTER implementation work is complete, including:',
      '- Writing or modifying production/source files for a feature or fix',
      '- Adding or updating tests as part of implementation',
      '- Addressing implementation review feedback',
      '',
      'Do NOT invoke this skill during design-only, planning-only, metadata-only, or feature-renaming work.',
      'Those tasks may need targeted consistency checks, but they are not post-implementation readiness gates.',
      '',
      '## How to Invoke',
      '',
      'Use the internal OpenFlow tool:',
      '',
      '`openflow-quality-gate`',
      '',
      'Pass no arguments. The tool detects context automatically.',
      '',
      '## What the Quality Gate Does',
      '',
      '1. **Visible Quality Gate Session** — Creates a top-level `Quality Gate: {feature}` session',
      '   that records stage progress: context/scope, applicability, risk, harden rounds, verify summary, and readiness.',
      '   Harden Reviewer and Executor sessions are linked as child sessions. The main conversation receives only a concise summary.',
      '2. **Applicability Classification** — First decides whether the current work is Applicable, NotApplicable, NeedsWorkflowStage, or LimitedContext.',
      '   - NotApplicable: design-only, planning-only, metadata-only, docs-only, or rename-only work does not need archive readiness.',
      '   - NeedsWorkflowStage: implementation/archive-like work is missing an explicit workflow stage; ask before entering that stage.',
      '   - LimitedContext: code/test fixes may receive valid technical verification without harden, but the result is not full semantic feature readiness or archive readiness.',
      '3. **Context Detection** — Identifies the semantic context (feature, issue, plan, or request)',
      '   from the workspace and history. This determines how the gate evaluates readiness.',
      '4. **Reflection Corrective Rule Check** — Reviews relevant corrective rules from',
      '   `docs/current/workflow/ai-reflection/` that may apply to the current task,',
      '   changed files, command flow, or verification behavior. This is an instruction-only',
      '   check: identify applicable rules and factor them into readiness reasoning.',
      '   If no related rules exist or reflection docs are absent, this is not a blocker',
      '   — proceed to the next step. Readiness Classification remains the final authority',
      '   on whether implementation is complete.',
      '5. **Harden Decision** — Decides whether adversarial quality hardening is required based on',
      '   change complexity, risk indicators, and cross-cutting concerns.',
      '   - Harden Reviewer judges implementation against approved contracts (decisions > current > behavior > design > plan > request > diff > implementation).',
      '   - Finding taxonomy includes: `behavior_violation`, `spec_violation`, `intent_gap`, `contract_divergence`, `regression_risk`, `missing_evidence`.',
      '   - `intent_gap` triggers an inference branch: high/medium confidence + aligned → accepted with doc update; misaligned → fix implementation; low/conflicting → needs decision.',
      '   - Executor only receives fixable implementation findings and does not silently modify docs or approve contract divergence.',
      '6. **Behavior Evidence Verification** — Validates behavior evidence from `.sisyphus/evidence/{scenario-id}-{slug}.md`.',
      '   - Critical scenarios require fresh exact or equivalent evidence with rationale.',
      '   - Missing, stale, or partial critical evidence blocks readiness.',
      '   - Optional or boundary evidence gaps are advisory unless marked blocking.',
      '7. **Verify Execution** — Runs evidence-aware verification that checks:',
      '   - Drift detection against approved design/requirements',
      '   - Quality checks (typecheck, lint, test, format)',
      '   - Security checks (secrets, vulnerabilities)',
      "   - Consistency with current system facts and decisions",
      '8. **Implementation Mapper Generation** — When readiness is Ready or ReadyWithDocUpdates',
      '   and a behavior.md exists, generates a lightweight implementation-mapper.md in the',
      '   changes workspace (docs/changes/{feature}/). This mapper records behavior scenarios',
      '   and their corresponding key code files for traceability.',
      '9. **Readiness Classification** — Returns one of: Ready, ReadyWithDocUpdates, NotReady,',
      '   or NeedsDecision. Blocking conditions are reported as NotReady or NeedsDecision with',
      '   reason codes, not as a separate status.',
      '   - `Ready` and `ReadyWithDocUpdates` map to `ready_for_archive` (Awaiting Archive Confirmation).',
      '   - Archive does NOT run automatically; explicit user confirmation is required.',
      '   - Limited-context results are not archive eligible by themselves.',
      '',
      '## Critical Rule',
      '',
      '```',
      'DO NOT CLAIM COMPLETION UNTIL THE QUALITY GATE REPORTS READINESS.',
      '```',
      '',
      'The quality gate is the final authority on whether implementation is technically verified for the available context.',
      'If it returns NotReady or NeedsDecision, address the issues and re-invoke the gate.',
      'If it returns NotApplicable, do not create missing docs; no implementation readiness gate is required.',
      'If it returns LimitedContext, treat the checks as valid technical verification for a post-hoc fix, not as semantic feature readiness; do not archive from that result unless a later archive path explicitly supports it.',
      'If it returns NeedsWorkflowStage, ask whether to enter the explicit OpenFlow workflow stage first.',
      'If full semantic readiness is blocked by missing workflow artifacts such as plan.md, design.md, behavior.md,',
      'or issue-clarification.md, report the blocker and suggest the explicit workflow command; do not require those artifacts for LimitedContext technical verification.',
      'Do not create missing workflow artifacts merely to satisfy the gate unless the user requested that stage.',
      '',
      '## What NOT to Do',
      '',
      '- Do NOT skip the quality gate after implementation code changes or bug fixes',
      '- Do NOT invoke the quality gate for design-only, planning-only, metadata-only, or feature-renaming tasks unless the user explicitly asks for readiness verification or archive readiness',
      '- Do NOT create plan.md, design.md, behavior.md, or issue-clarification.md merely to make the gate pass',
      '- Do NOT claim "looks good" or "should pass" before invoking',
      '- Do NOT tell the user to manually run /openflow-harden or /openflow-verify',
      '- Do NOT rely on stale verification from a previous invocation',
      '- Do NOT automatically invoke /openflow-archive after the quality gate returns Ready or ReadyWithDocUpdates',
      '- Do NOT treat quality gate readiness as user acceptance; readiness is a technical verification result, not a delivery approval',
      '- Report the quality gate result to the user and wait for explicit confirmation before proceeding to archive',
    ].join('\n'),
  }
}
