import type { SkillInfo } from './types.js'

export function getQualityGateSkill(): SkillInfo {
  return {
    name: 'openflow-quality-gate',
    description: 'Quality Gate executed after code changes or bug fixes. AI should call openflow-quality-gate and not claim completion until readiness is returned.',
    content: [
      '# OpenFlow Quality Gate Skill',
      '',
      '## Overview',
      '',
      'The quality gate is an AI-callable verification that runs after implementation code changes or bug fixes.',
      'It is NOT a user slash command — it is invoked by the AI during implementation.',
      '',
      '## When to Invoke',
      '',
      'Invoke this skill AFTER implementation work is complete, including:',
      '- Writing or modifying production/source files for a feature or fix',
      '- Adding or updating tests as part of implementation',
      '- Addressing implementation review feedback',
      '',
      'Do NOT invoke this skill during design-only, planning-only, metadata-only, or feature-renaming work.',
      'Those tasks may need targeted consistency checks, but they are not post-implementation readiness gates.',
      '',
      '## How to Invoke',
      '',
      'Use the internal OpenFlow tool:',
      '',
      '`openflow-quality-gate`',
      '',
      'Pass no arguments. The tool detects context automatically.',
      '',
      '## What the Quality Gate Does',
      '',
      '1. **Applicability Classification** — First decides whether the current work is Applicable, NotApplicable, NeedsWorkflowStage, or LimitedContext.',
      '   - NotApplicable: design-only, planning-only, metadata-only, docs-only, or rename-only work does not need archive readiness.',
      '   - NeedsWorkflowStage: implementation/archive-like work is missing an explicit workflow stage; ask before entering that stage.',
      '   - LimitedContext: technical checks may run, but the result is not full semantic or archive readiness.',
      '2. **Context Detection** — Identifies the semantic context (feature, issue, plan, or request)',
      '   from the workspace and history. This determines how the gate evaluates readiness.',
      '3. **Reflection Corrective Rule Check** — Reviews relevant corrective rules from',
      '   `docs/current/workflow/ai-reflection/` that may apply to the current task,',
      '   changed files, command flow, or verification behavior. This is an instruction-only',
      '   check: identify applicable rules and factor them into readiness reasoning.',
      '   If no related rules exist or reflection docs are absent, this is not a blocker',
      '   — proceed to the next step. Readiness Classification remains the final authority',
      '   on whether implementation is complete.',
      '4. **Harden Decision** — Decides whether adversarial quality hardening is required based on',
      '   change complexity, risk indicators, and cross-cutting concerns.',
      '5. **Evidence Collection** — If harden is needed, the gate runs it and collects results.',
      '6. **Verify Execution** — Runs evidence-aware verification that checks:',
      '   - Drift detection against approved design/requirements',
      '   - Quality checks (typecheck, lint, test, format)',
      '   - Security checks (secrets, vulnerabilities)',
      "   - Consistency with current system facts and decisions",
      '7. **Implementation Mapper Generation** — When readiness is Ready or ReadyWithDocUpdates',
      '   and a behavior.md exists, generates a lightweight implementation-mapper.md in the',
      '   changes workspace (docs/changes/{feature}/). This mapper records behavior scenarios',
      '   and their corresponding key code files for traceability.',
      '8. **Readiness Classification** — Returns one of: Ready, ReadyWithDocUpdates, NotReady,',
      '   or NeedsDecision. Blocking conditions are reported as NotReady or NeedsDecision with',
      '   reason codes, not as a separate status.',
      '',
      '## Critical Rule',
      '',
      '```',
      'DO NOT CLAIM COMPLETION UNTIL THE QUALITY GATE REPORTS READINESS.',
      '```',
      '',
      'The quality gate is the final authority on whether implementation is complete.',
      'If it returns NotReady or NeedsDecision, address the issues and re-invoke the gate.',
      'If it returns NotApplicable, do not create missing docs; no implementation readiness gate is required.',
      'If it returns LimitedContext, treat any checks as technical-only and do not archive from that result.',
      'If it returns NeedsWorkflowStage, ask whether to enter the explicit OpenFlow workflow stage first.',
      'If readiness is blocked by missing workflow artifacts such as plan.md, design.md, behavior.md,',
      'or issue-clarification.md, report the blocker and suggest the explicit workflow command.',
      'Do not create missing workflow artifacts merely to satisfy the gate unless the user requested that stage.',
      '',
      '## What NOT to Do',
      '',
      '- Do NOT skip the quality gate after implementation code changes or bug fixes',
      '- Do NOT invoke the quality gate for design-only, planning-only, metadata-only, or feature-renaming tasks unless the user explicitly asks for readiness verification or archive readiness',
      '- Do NOT create plan.md, design.md, behavior.md, or issue-clarification.md merely to make the gate pass',
      '- Do NOT claim "looks good" or "should pass" before invoking',
      '- Do NOT tell the user to manually run /openflow-harden or /openflow-verify',
      '- Do NOT rely on stale verification from a previous invocation',
      '- Do NOT automatically invoke /openflow-archive after the quality gate returns Ready or ReadyWithDocUpdates',
      '- Do NOT treat quality gate readiness as user acceptance; readiness is a technical verification result, not a delivery approval',
      '- Report the quality gate result to the user and wait for explicit confirmation before proceeding to archive',
    ].join('\n'),
  }
}
