import type { SkillInfo } from './types.js'

export function getQualityGateSkill(): SkillInfo {
  return {
    name: 'openflow-quality-gate',
    description: 'Quality Gate executed after code changes or bug fixes. AI should call openflow-quality-gate and not claim completion until readiness is returned.',
    content: [
      '# OpenFlow Quality Gate Skill',
      '',
      '## Overview',
      '',
      'The quality gate is an AI-callable verification that runs after code changes or bug fixes.',
      'It is NOT a user slash command — it is invoked by the AI during implementation.',
      '',
      '## When to Invoke',
      '',
      'Invoke this skill AFTER all code changes for a task are complete, including:',
      '- Writing or modifying source files',
      '- Adding or updating tests',
      '- Addressing review feedback',
      '',
      'Do NOT invoke this skill during the design or planning phase.',
      '',
      '## How to Invoke',
      '',
      'Use the internal OpenFlow tool:',
      '',
      '`openflow-quality-gate`',
      '',
      'Pass no arguments. The tool detects context automatically.',
      '',
      '## What the Quality Gate Does',
      '',
      '1. **Context Detection** — Identifies the semantic context (feature, issue, plan, or request)',
      '   from the workspace and history. This determines how the gate evaluates readiness.',
      '2. **Harden Decision** — Decides whether adversarial quality hardening is required based on',
      '   change complexity, risk indicators, and cross-cutting concerns.',
      '3. **Evidence Collection** — If harden is needed, the gate runs it and collects results.',
      '4. **Verify Execution** — Runs evidence-aware verification that checks:',
      '   - Drift detection against approved design/requirements',
      '   - Quality checks (typecheck, lint, test, format)',
      '   - Security checks (secrets, vulnerabilities)',
      "   - Consistency with current system facts and decisions",
       '5. **Readiness Classification** — Returns one of: Ready, ReadyWithDocUpdates, NotReady,',
       '   or NeedsDecision. Blocking conditions are reported as NotReady or NeedsDecision with',
       '   reason codes, not as a separate status.',
      '',
      '## Critical Rule',
      '',
      '```',
      'DO NOT CLAIM COMPLETION UNTIL THE QUALITY GATE REPORTS READINESS.',
      '```',
      '',
      'The quality gate is the final authority on whether implementation is complete.',
      'If it returns NotReady or NeedsDecision, address the issues and re-invoke the gate.',
      '',
      '## What NOT to Do',
      '',
      '- Do NOT skip the quality gate even for "trivial" changes',
      '- Do NOT claim "looks good" or "should pass" before invoking',
      '- Do NOT tell the user to manually run /openflow-harden or /openflow-verify',
      '- Do NOT rely on stale verification from a previous invocation',
    ].join('\n'),
  }
}
