import type { SkillInfo } from './types.js'

export function getWritingPlanSkill(): SkillInfo {
  return {
    name: 'openflow-writing-plan',
    description: 'Manual command reference for /openflow-writing-plan. Use only when the user explicitly requests /openflow-writing-plan or an implementation/development plan; never invoke from stuck /openflow-feature, brainstorm, or ULW flow. When OMO is detected, execution routes to Prometheus. OpenFlow creates a hard link from .sisyphus/plans/ to docs/changes/*/plan.md so Prometheus writes directly into the canonical path. When non-OMO, execution routes to the OpenCode build agent (not plan agent — plan agent is read-only); the build agent writes the plan.md file to docs/changes/*/plan.md, then stops.',
    content: [
      '# OpenFlow Writing-Plan Command Reference',
      '',
      '## Authority',
      '',
      'The `/openflow-writing-plan <feature>` command output is the **authoritative** format template for the current configuration (TDD enabled/disabled, OMO detected/non-OMO). This skill document provides the complete reference covering all variants; always defer to the command output when there is a conflict.',
      '',
      '## Overview',
      '',
      '**Writing plans IS structured execution planning applied to feature development.**',
      '',
      '**Core principle: Every line in your plan must survive copy-paste into task execution. If a line needs rewriting by the executor, it should not be in the plan.**',
      '',
      'A future executor will read this plan to decide what to do, not to admire prose. Optimize for scanning: headings first, then bullets, then code blocks, then prose.',
      '',
      '**Plans are:** Structured, executable, traceable task trees with clear boundaries.',
      '**Plans are NOT:** Design documents, requirement specs, or prose summaries of intent.',
      '',
      '`/openflow-writing-plan` supports `--mode=pyramid|pattern|mixed|false` (default: false). The mode determines the planning methodology:',
      '- `pyramid`: Pyramid Principle planning (highest-level goal, task pyramid, core abstractions)',
      '- `pattern`: Design-pattern-oriented planning (identified patterns, component responsibilities, collaboration model)',
      '- `mixed`: AI chooses the best approach (pyramid, pattern, or combination)',
      '- `false`: Direct decomposition without enforcing a specific methodology',
      '',
      'When TDD is enabled (the command output will specify), TDD maps abstraction nodes to observable behavior and Red-Green-Refactor execution order regardless of mode.',
      'In OMO environments, OpenFlow creates a hard link from `.sisyphus/plans/{feature}.md` to `docs/changes/YYYY-MM-DD-{feature}/plan.md`. Prometheus writes to the `.sisyphus/plans/` path, which modifies the canonical file directly. No copying is needed.',
      'In non-OMO environments, the OpenCode build agent generates the plan and writes it to disk. The build agent is used (not the plan agent) because the plan agent is read-only. The **final plan must exist at `docs/changes/YYYY-MM-DD-{feature}/plan.md`** before execution begins.',
      '',
      'OpenFlow\'s plan enhancer may inject additional guidance when configured.',
      '',
      '### Pyramid → Plan Mapping',
      '',
      'Read this table before writing a plan. Every plan section maps to a Pyramid concept:',
      '',
      '| Pyramid Concept | Plan Artifact |',
      '|-----------------|---------------|',
      '| Highest-level goal | `### Highest-Level Goal` section |',
      '| Task pyramid | `## Tasks` ordered by dependency depth |',
      '| Core abstraction boundary | Task-level "Agent Profile" with explicit boundary |',
      '| Layer separation | Wave separation (Wave N never depends on Wave N+1) |',
      '| TDD behavior mapping | `### TDD Driving Order` (RED/GREEN/REFACTOR per abstraction) — include when TDD is enabled |',
      '',
      '## When to Use',
      '',
      'Invoke this skill **only** when:',
      '- The user explicitly requests `/openflow-writing-plan <feature>`, OR',
      '- The user asks for an implementation or development plan by name.',
      '',
      '**Do NOT invoke** when:',
      '- `/openflow-feature` is active, stuck, or incomplete — it still owns requirement clarification.',
      '- Feature design is not yet finalized — write `design.md` and `behavior.md` first.',
      '- Brainstorm or ULW/ultrawork flow is active — those have their own output artifacts.',
      '',
      '```',
      '❌ BAD:  "The user just finished /openflow-feature, so I should auto-run writing-plan."',
      '✅ GOOD: "Feature design is complete. If you want an execution plan next, run: /openflow-writing-plan <feature>"',
      '```',
      '',
      '## Agent Target',
      '',
      '- **OMO detected** → Prometheus (interview, clearance, and execution)',
      '- **Non-OMO** → OpenCode native `build` agent (plan agent is read-only and cannot write plan.md)',
      '',
      'Agent selection is program-enforced. OpenFlow prepares the design context and constraints; the target agent owns the planning conversation.',
      '',
      '## Public Entry',
      '',
      '`/openflow-writing-plan <feature>`',
      '',
      '## Required Workflow',
      '',
      'Follow these steps in order. Do not skip or reorder them.',
      '',
      '### Step 1: Scope Check',
      '',
      'Before writing any plan, verify design readiness. Follow the flowchart:',
      '',
      '```dot',
      'digraph scope_check {',
      '    rankdir=TD;',
      '    node [shape=diamond];',
      '   design_exists [label="design.md exists\\nfor this feature?"];',
      '    design_complete [label="state.md has\\n`complete` status?"];',
      '    behavior_exists [label="behavior.md exists?"];',
      '    node [shape=box];',
      '   stop_feature [label="STOP.\\nSuggest: /openflow-feature <feature>", style=filled, fillcolor="#ffcccc"];',
      '    stop_resume [label="STOP.\\nSuggest: resume feature clarification", style=filled, fillcolor="#ffcccc"];',
      '    stop_behavior [label="STOP.\\nSuggest: run /openflow-feature to generate behavior.md", style=filled, fillcolor="#ffcccc"];',
      '   proceed [label="Proceed to Step 2", style=filled, fillcolor="#ccffcc"];',
      '    design_exists -> design_complete [label="yes"];',
      '    design_exists -> stop_feature [label="no"];',
      '    design_complete -> behavior_exists [label="yes"];',
      '    design_complete -> stop_resume [label="no"];',
      '    behavior_exists -> proceed [label="yes"];',
      '    behavior_exists -> stop_behavior [label="no"];',
      '}',
      '```',
      '',
      'Additional scope rules:',
      '- If requirements or design context are unclear, **stop and ask clarifying questions**. Do NOT generate a plan with `DECISION-NEEDED` placeholders.',
      '- When Prometheus is the target agent, let Prometheus perform its own interview and clearance checks. OpenFlow only supplies the design context packet.',
      '',
      '### Step 2: File Structure',
      '',
      'Identify and verify the expected output files (paths come from configuration, not hardcoded values):',
      '- OMO: OpenFlow creates a hard link from `.sisyphus/plans/{feature}.md` to `{config.paths.changes}/YYYY-MM-DD-{feature}/plan.md`. Prometheus writes to the `.sisyphus/plans/` path, which modifies the canonical file directly.',
      '- Non-OMO: The build agent generates the plan and writes it directly to `{config.paths.changes}/YYYY-MM-DD-{feature}/plan.md` (default: `docs/changes/...`). The plan agent is not used because it is read-only. The build agent writes the plan, then stops. STOP guardrails in the command packet prevent it from proceeding to implementation.',
      '- Ensure parent directories exist before writing.',
      '- If the plan file already exists, tell the user and ask whether to overwrite or keep it. Do NOT silently overwrite.',
      '- If the OMO workspace copy already has checked tasks, treat it as execution state and do not overwrite it just to restore identity with the canonical plan.',
      '',
      '### Step 3: Plan Structure',
      '',
      'The plan document has exactly six top-level sections, in this order:',
      '',
      '1. `# Plan: {feature}` — heading',
      '2. `## Overview` — one paragraph summarizing the feature',
      '3. `## Design Context` — reference to the design workspace',
      '4. `## Strategy` — the structural heart of the plan (see Step 4). The exact heading depends on the mode: `## Pyramid Strategy`, `## Pattern Strategy`, `## Mixed Strategy`, or `## Planning Strategy`. When TDD is enabled, the heading includes "+ TDD" (e.g., `## Pyramid + TDD Strategy`).',
      '5. `## Execution Strategy` — parallel waves and dependency matrix',
      '6. `## Tasks` — checkbox or numbered tasks (parser-compatible)',
      '',
      'No additional top-level sections. Sub-sections may be added as needed inside the Strategy and Execution Strategy sections.',
      '',
      '### Step 4: Task Rules',
      '',
      'The `## Tasks` section is critical. Every line must be a checkbox item (`- [ ] ...`) or a numbered item (`1. ...`) with a clear title.',
      '',
      '**Planning Rules by Mode:**',
      '',
      '- **pyramid mode**: Pyramid Principle owns structure — highest-level goal, task pyramid, core abstractions, boundaries, and grouping.',
      '- **pattern mode**: Follow the 6-step pattern workflow (Problem Analysis → Pattern Selection → Contracts → Components → Collaborations → Verification). Each step produces concrete artifacts that map directly to tasks.',
      '- **mixed mode**: First classify the feature (process complexity vs architectural complexity), then apply Pyramid (if process-heavy), Pattern (if architecture-heavy), or both with cross-consistency checks.',
      '- **false mode (default)**: No specific methodology is enforced. Decompose requirements directly into executable tasks.',
      '- Do NOT turn planning into complete upfront design. Capture only the abstractions needed to guide implementation (and tests when TDD is enabled).',
      '- When TDD is enabled: TDD owns behavior — each core abstraction or business rule must map to observable tests and a Red-Green-Refactor sequence. Do NOT let TDD become unstructured test accumulation.',
      '- Simple plans may omit detailed strategy sections only when the plan explains why the work is simple and still provides verification commands.',
      '',
      '**Pattern Mode Detailed Workflow:**',
      '',
      'When the command output indicates Pattern mode, follow these 6 steps in order:',
      '',
      '1. **Problem Analysis**: Identify structural problems (object creation, behavioral variation, decoupling, adaptation, composition). Write one sentence per problem. DO NOT force a pattern.',
      '2. **Pattern Selection**: Map each problem to a specific pattern with rationale. Prefer GoF or well-known architectural patterns. Document why this pattern beats simpler alternatives.',
      '3. **Define Contracts**: For each pattern, write interfaces with methods, signatures, preconditions, postconditions, and error contracts.',
      '4. **Implement Components**: List each concrete component with file path, class name, responsibility, boundary (what it does NOT do), and dependencies.',
      '5. **Wire Collaborations**: Describe instantiation, data flow, control flow, lifecycle, and error propagation between components.',
      '6. **Verification Checklist**: Confirm no over-engineering, single responsibility per component, dependency DAG (no cycles), and KISS respected.',
      '',
      '**Mixed Mode Detailed Workflow:**',
      '',
      'When the command output indicates Mixed mode, follow this 4-phase workflow:',
      '',
      'Phase 1 — Classify: Answer four questions (process complexity, architectural complexity, structural reuse, data flow complexity). Based on answers, choose Pyramid only, Pattern only, Both, or Neither.',
      'Phase 2 — Apply Pyramid (if selected): Write Highest-Level Goal, Task Pyramid, and Process Boundaries.',
      'Phase 3 — Apply Pattern (if selected): Follow the 6-step pattern workflow above.',
      'Phase 4 — Cross-Consistency: If both selected, verify Pyramid tasks respect Pattern boundaries and Pattern components fit into Pyramid waves. Identify shared abstractions and define them first.',
      '',
      '**Task Decomposition Rules:**',
      '- Group independent tasks into execution waves. Same-wave tasks are candidates for parallel execution.',
      '- Each task should be an independently deliverable work package with a clear boundary.',
      '- A single task may cover a few closely related files in the same module.',
      '- Do NOT mechanically create one task per file. Prefer cohesive work packages (see Red Flags below).',
      '- Limit same-wave concurrency: default max 3–4 tasks per wave unless justified.',
      '- Every task must include: Agent Profile (recommended category + skills), Parallelization status, Acceptance Criteria.',
      '- Include a Dependency Matrix: `| Task | Blocked By | Blocks |`.',
      '- After writing the plan, estimate total execution units (tasks × sub-items). If exceeded 20 units or same-wave > 4 tasks, merge smaller tasks or increase wave count.',
      '',
      'The plan must follow this structure:',
      '',
      '```markdown',
      '# Plan: {feature}',
      '',
      '## Overview',
      'Brief description of what this feature accomplishes.',
      '',
      '## Design Context',
      'Reference to the design workspace (e.g., `docs/changes/YYYY-MM-DD-{feature}/`).',
      '',
      '## Pyramid Strategy',
      '<!-- OR "## Pyramid + TDD Strategy" when TDD is enabled -->',
      '',
      '### Highest-Level Goal',
      'One sentence describing the business or workflow outcome this plan delivers.',
      '',
      '### Task Pyramid',
      '1. Top-level work group',
      '   1.1 Same-level subtask',
      '   1.2 Same-level subtask',
      '',
      '### Core Abstractions and Boundaries',
      '- Abstraction: responsibility, boundary, and what must stay outside it.',
      '',
      '### TDD Driving Order',
      '<!-- Include this section when TDD is enabled -->',
      '1. RED: failing test for the highest-level observable behavior',
      '2. GREEN: minimal implementation for that behavior',
      '3. REFACTOR: check abstraction level, naming, and grouping while tests stay green',
      '',
      '## Execution Strategy',
      '',
      '### Parallel Execution Waves',
      'Wave 1: Tasks with no dependencies',
      'Wave 2: Tasks depending on Wave 1 results',
      '',
      '### Dependency Matrix',
      '| Task | Blocked By | Blocks |',
      '',
      '## Tasks',
      '- [ ] 1. Task name (Agent: quick | Blocks: [...] | Blocked By: [...])',
      '- [ ] 2. Another task',
      '```',
      '',
      'The parser ignores any line that does not match these formats — unrecognized lines are silently dropped and will not appear in the task list.',
      '',
      '### Step 5: No Placeholders',
      '',
      'Every task must be concrete and executable:',
      '- **No TBD, TODO, or "implement later"** in any task.',
      '- Every task specifies exact file paths to create or modify.',
      '- Every task includes a runnable verification command and expected output.',
      '',
      '### Step 6: Preserve Constraints',
      '',
      'Design constraints must travel with every task that is affected by them. Do not silently drop constraints established during feature design.',
      '',
      'Concrete actions:',
      '- Read `design.md` and `behavior.md` once before writing any task.',
      '- Copy severity-tagged constraints (e.g., `[HIGH / security]`) into the body of every task they affect.',
      '- Verify each task\'s acceptance criteria echoes the corresponding acceptance criteria from the design packet.',
      '- If a task has no constraint to carry forward, leave it unconstrained — do not invent constraints.',
      '',
      '### Step 7: Self-Review',
      '',
      'Before finalizing, run this lightweight self-check against the plan:',
      '',
      '- **No placeholders**: Every task has a specific file path, not "somewhere in src/".',
      '- **Concrete verification**: Every task names a real command (e.g., `npm test -- path/to/test`, `npx tsc --noEmit`).',
      '- **Strategy fit present when needed**: Non-simple requirements include structure from the chosen approach (highest-level goal / identified patterns / task pyramid / component responsibilities) and abstraction boundaries. When TDD is enabled, also include TDD driving order and Red-Green-Refactor checkpoints.',
      '- **Bounded complexity**: No single task describes an unreasonable amount of work. If a task spans more than 3–4 closely related files, split it.',
      '- **Task count**: Total tasks should be proportional to feature size: small features 3–5 tasks, medium 6–9, large 10–15.',
      '- **Parser-compatible**: The `## Tasks` section uses checkbox or numbered items exclusively.',
      '- **Quality gate present**: After formal implementation work is complete and Full Quality Gate admission criteria are met, invoke the openflow-quality-gate skill. Do not claim completion until the quality gate reports readiness. For casual coding or low-risk edits, use lightweight verification instead of automatically invoking Full Quality Gate.',
      '',
      '### Step 8: STOP. Hand Off.',
      '',
      '**After the plan file is saved to disk, you MUST STOP. Do not proceed.**',
      '',
      '**Do NOT:**',
      '- Begin executing any task in the plan.',
      '- Create or run an `executing-plans` or `start-work` command.',
      '- Invoke OMO, Prometheus, or `/openflow-implement` on your own.',
      '- Append OpenCode task blocks, verification commands, or ad-hoc harden steps to the plan.',
      '- Assume the plan was approved just because it was written.',
      '',
      '**Your role ends when the file bytes are written.** The user will provide the plan to their execution environment:',
      '- If **Prometheus** is the target: hand off to Prometheus for interview, clearance, and execution.',
      '- If **build** agent is the target: hand off to OpenCode native `build` agent. It writes the plan file, then stops.',
      '',
      'The implementation entrypoint is `/openflow-implement <feature>`, invoked by the user, not by you.',
      '',
      '## Common Rationalizations',
      '',
      'When writing plans, agents frequently rationalize shortcuts. Counter each explicitly:',
      '',
      '| Rationalization | Reality |',
      '|-----------------|---------|',
      '| "Design is thin — I\'ll assume the intent and proceed." | Thin design calls for MORE structure, not less. Stop and ask — never proceed with placeholders. |',
      '| "Task names are obvious, skip the Strategy section." | "Obvious" names hide ambiguous boundaries. The Strategy section forces clarity for the executor. |',
      '| "This is a small feature, skip the template." | Small features still need verification commands. Keep all six sections; simplify content, not structure. |',
      '| "One mega-task covers everything cohesively." | Cohesion ≠ size. Split by abstraction boundary — three 2-file tasks beat one 6-file task. |',
      '| "Plan looks complete — skip Self-Review." | Self-Review catches structural drift. Seven criteria × 5 seconds = cheap insurance. |',
      '',
      '## 🚩 Red Flags',
      '',
      'If any of these appear in the plan you are writing, STOP and fix the structural issue before proceeding:',
      '',
      '- Any placeholder text remains (`TODO`, `TBD`, `somewhere in src/`, `DECISION-NEEDED`).',
      '- Task names are full sentences or exceed 10 words — probably hiding multiple tasks.',
      '- The same file appears in 3 or more different tasks — boundary failure, consolidate or split differently.',
      '- Zero verification commands exist in the entire plan — the executor will have no way to confirm success.',
      '- A wave depends on something not yet complete in earlier waves — fix the dependency structure.',
      '- The plan lacks `## Tasks` or the section contains prose instead of checkbox/numbered items.',
      '',
      '**All of these mean: Stop. Fix the structural issue. Do not continue filling in tasks on a broken skeleton.**',
      '',
      '## Plan Writing Checklist',
      '',
      'Scan at each phase. Check every box before moving to the next phase.',
      '',
      '**Before writing:**',
      '- [ ] Scope Check flowchart returns Proceed (design docs exist and complete)',
      '- [ ] Feature identity resolved in design packet',
      '',
      '**While writing:**',
      '- [ ] All six top-level sections present, in order',
      '- [ ] Strategy section (Pyramid / Pattern / Mixed / Planning) filled with concrete content for non-simple requirements',
      '- [ ] Every task has: file path + verification command + agent profile',
      '- [ ] Wave boundaries match the Dependency Matrix',
      '- [ ] Design constraints carried forward into affected tasks (Step 6)',
      '',
      '**After writing:**',
      '- [ ] Self-Review passes all seven criteria (Step 7)',
      '- [ ] No Red Flags remain',
      '- [ ] Quality gate invocation instruction present in the last QA task',
      '- [ ] STOP. File saved. Do not execute. Do not invoke downstream commands.',
      '',
      '## Real-World Impact',
      '',
      'A well-written plan produces visible differences downstream. Use this table to self-evaluate your plan quality:',
      '',
      '| Symptom | Bad plan | Good plan |',
      '|---------|----------|-----------|',
      '| Executor asks clarifying questions | On every task | Never — the plan is self-contained. |',
      '| Wave N+1 needs re-scoping after Wave N | Frequently | Rarely — the strategy section enforces dependency truth. |',
      '| Placeholder text survives into execution | Common | Zero — Step 5 is a hard gate. |',
      '| Same file appears across multiple tasks | 3–4 tasks touch it | Rare — boundary awareness prevents this. |',
      '| Human review catches structural drift | Yes | Self-Review (Step 7) catches 95%+ before human sees it. |',
      '',
      '**The Core Principle is your only self-check metric:** `Every line in your plan must survive copy-paste into task execution. If a line needs rewriting by the executor, it should not be in the plan.`',
      '',
      'If you cannot answer "yes" to this statement for every line in your plan, stop and fix it before handing off.',
      '',
      '## Quality Gate Instruction',
      '',
      'The final implementation/QA task must instruct the executor to invoke the `openflow-quality-gate` skill after formal implementation work is complete and Full Quality Gate admission criteria are met.',
      '',
      'Use this wording:',
      '',
      '`After formal implementation is complete and Full Quality Gate admission criteria are met, invoke the openflow-quality-gate skill. The skill decides whether harden is required and performs evidence-aware verify. Do not claim completion until the quality gate reports readiness. For casual coding or low-risk edits, use lightweight verification instead.`',
      '',
      'Do NOT tell the user to manually run `/openflow-harden` or `/openflow-verify`.',
      '',
      '## OMO / Prometheus Compatibility',
      '',
      '- This skill does NOT replace or disable any OMO/Prometheus built-in capabilities. Prometheus exploration, brainstorming, and task planning features remain fully available.',
      '- When invoked inside a Prometheus session, use this skill to produce the plan artifact, then let Prometheus continue its normal workflow (plan selection, execution, review).',
      '- In OMO environments, OpenFlow creates a hard link from `.sisyphus/plans/` to `docs/changes/`. Prometheus writes to `.sisyphus/plans/`, which modifies the canonical file directly.',
      '- In non-OMO environments, the OpenCode build agent generates and writes the plan directly to `docs/changes/`. No intermediate copy or plan_exit step is needed.',
      '- After execution starts, the OMO workspace copy may diverge as the execution engine records task progress; the `docs/changes/` plan remains the canonical planning artifact.',
      '- **Prometheus Precedence**: If any instruction in this skill conflicts with Prometheus behavior (e.g., interview mode, clearance checks, QA scenarios), Prometheus wins. OpenFlow supplies the design context; Prometheus owns the planning conversation.',
      '',
      '## Notes',
      '',
      '- This command produces a development plan, not a design document. Design work should already be complete before planning begins.',
      '- If design docs are missing, the user should run `/openflow-feature` first.',
      '- Plans are living documents during implementation. After saving the initial version, the user or execution engine may update tasks as work progresses.',
      '- Output paths come from OpenFlow configuration; `docs/changes/` and `.openflow/plans/` are defaults, not hardcoded requirements.',
    ].join('\n'),
  }
}
