import type { SkillInfo } from './types.js'

export function getWritingPlanSkill(): SkillInfo {
  return {
    name: 'openflow-writing-plan',
    description: 'Manual command reference for /openflow-writing-plan when the user wants to create a development plan for a feature. It prepares plan-writing context, then writes a structured plan to docs/changes/*/plan.md (and .sisyphus/plans/{feature}.md if OMO is present).',
    content: [
      '# OpenFlow Writing-Plan Command Reference',
      '',
      '## Overview',
      '',
      'This help text documents the manual `/openflow-writing-plan` command for producing a focused, parser-compatible development plan',
      'for a feature. The primary plan artifact lives in the change workspace (`docs/changes/YYYY-MM-DD-{feature}/plan.md`).',
      'If oh-my-openagent (OMO) / Prometheus is detected, also save an identical initial copy to `.sisyphus/plans/{feature}.md` for execution engine consumption.',
      'The copies must match when first saved; after execution starts, the `.sisyphus/plans/` copy may diverge as task progress is recorded.',
      "OpenFlow's plan enhancer may inject TDD guidance when configured.",
      '',
      '## Public Entry',
      '',
      'Start with:',
      '',
      '`/openflow-writing-plan <feature>`',
      '',
      '## Required Workflow',
      '',
      'Follow these steps in order. Do not skip or reorder them.',
      '',
      '### Step 1: Invoke the Internal Tool',
      '',
      'Use the internal OpenFlow tool:',
      '',
      '`openflow-writing-plan <feature>`',
      '',
      'Pass the feature name exactly. The tool returns a plan-writing packet',
      'with design context, requirements, and any discovered constraints.',
      '',
      '### Step 2: Read the Plan-Writing Packet',
      '',
      'Read the output from the internal tool carefully. The packet contains:',
      'the feature name, the design workspace path, relevant design decisions,',
      'and any constraints you must respect when drafting the plan.',
      '',
      '### Step 3: Check for Existing Plans',
      '',
      'Before writing, check whether a plan already exists:',
      '- `docs/changes/YYYY-MM-DD-{feature}/plan.md` (change workspace primary)',
      '- `.sisyphus/plans/{feature}.md` (OMO execution copy)',
      'If either exists, tell the user and ask whether to overwrite or keep it.',
      'Do NOT silently overwrite an existing plan.',
      '',
      '### Step 4: Write the Plan',
      '',
      'Write the development plan to `docs/changes/YYYY-MM-DD-{feature}/plan.md`.',
      'If oh-my-openagent (OMO) / Prometheus is present (detected by `.sisyphus/` directory',
      'or `oh-my-openagent` config), also save an identical initial copy to `.sisyphus/plans/{feature}.md`.',
      'The two copies must be identical at initial save time — this is one plan, saved to two locations.',
      'After `/start-work`, OMO, or Prometheus begins execution, `.sisyphus/plans/{feature}.md` may diverge by recording task status/progress; do not treat that execution-state drift as a planning error.',
      '',
      '**Task Decomposition Rules:**',
      '- Group independent tasks into execution waves. Same-wave tasks are candidates for parallel execution.',
      '- Each task should be an independently deliverable work package with a clear boundary.',
      '- A single task may cover a few closely related files in the same module.',
      '- Do NOT mechanically create one task per file. Prefer cohesive work packages.',
      '- Limit same-wave concurrency: default max 3–4 tasks per wave unless justified.',
      '- Every task must include: Agent Profile (recommended category + skills), Parallelization status, Acceptance Criteria.',
      '- Include a Dependency Matrix: `| Task | Blocked By | Blocks |`.',
      '- After writing the plan, estimate total execution units (tasks × sub-items). If exceeded 20 units or same-wave > 4 tasks, merge smaller tasks or increase wave count.',
      '',
      'The plan must follow this structure:',
      '',
      '```markdown',
      '# Plan: {feature}',
      '',
      '## Overview',
      'Brief description of what this feature accomplishes.',
      '',
      '## Design Context',
      'Reference to the design workspace (e.g., `docs/changes/YYYY-MM-DD-{feature}/`).',
      '',
      '## Execution Strategy',
      '',
      '### Parallel Execution Waves',
      'Wave 1: Tasks with no dependencies',
      'Wave 2: Tasks depending on Wave 1 results',
      '',
      '### Dependency Matrix',
      '| Task | Blocked By | Blocks |',
      '',
      '## Tasks',
      '- [ ] 1. Task name (Agent: quick | Blocks: [...] | Blocked By: [...])',
      '- [ ] 2. Another task',
      '```',
      '',
      'The `## Tasks` section is critical. Every line must be a checkbox item',
      '(`- [ ] ...`) or a numbered item (`1. ...`) with a clear title.',
      'The parser ignores any line that does not match these formats.',
      '',
      '### Step 5: Keep the Plan Implementation-Focused',
      '',
      'Write tasks as implementation instructions with concrete paths and commands.',
      'Do NOT hardcode TDD expansion into every task. The existing OpenFlow plan',
      'enhancer automatically adds Red-Green-Refactor steps when TDD is enabled',
      'in the configuration. Your job is to produce a clean, executable plan that',
      'the enhancer can layer onto.',
      '',
      '### Step 6: Self-Check Before Saving',
      '',
      'Before finalizing, run this lightweight self-check against the plan:',
      '',
      '- **No placeholders**: Every task has a specific file path, not "somewhere in src/".',
      '- **Concrete verification**: Every task names a real command (e.g., `npm test -- path/to/test`, `npx tsc --noEmit`).',
      '- **Bounded complexity**: No single task describes an unreasonable amount of work. If a task spans more than 3–4 closely related files, split it.',
      '- **Task count**: Total tasks should be proportional to feature size: small features 3–5 tasks, medium 6–9, large 10–15.',
      '- **Parser-compatible**: The `## Tasks` section uses checkbox or numbered items exclusively.',
      '',
      '### Step 7: Add Quality Gate Instruction',
      '',
      'The final implementation/QA task must instruct the executor to invoke the',
      '`openflow-quality-gate` skill after all code changes are complete.',
      '',
      'Use this wording:',
      '',
      '`After implementation is complete, invoke the openflow-quality-gate skill. The skill decides whether harden is required and performs evidence-aware verify. Do not claim completion until the quality gate reports readiness.`',
      '',
      'Do NOT tell the user to manually run `/openflow-harden` or `/openflow-verify`.',
      '',
      '### Step 8: Stop After Saving',
      '',
      'After the plan file is written, **stop**. Do not execute the plan.',
      'Do not create or suggest an `executing-plans` command.',
      'Do not invoke OMO, Prometheus, or any execution agent.',
      'Do not add OpenCode task blocks, start-work commands, or manual harden/verify commands.',
      '',
      'The user will provide the plan document to their execution environment',
      '(OpenCode native tasks, oh-my-openagent, or manual execution).',
      'Your role ends when the file is saved.',
      '',
      '## OMO / Prometheus Compatibility',
      '',
      '- This skill does NOT replace or disable any OMO/Prometheus built-in capabilities.',
      '  Prometheus exploration, brainstorming, and task planning features remain fully available.',
      '- When invoked inside a Prometheus session, use this skill to produce the plan artifact,',
      '  then let Prometheus continue its normal workflow (plan selection, execution, review).',
      '- The dual-save ensures Prometheus can find the plan in `.sisyphus/plans/` without',
      '  needing to look into `docs/changes/`.',
      '- Initial dual-save identity is required only before execution starts. Once execution starts,',
      '  `.sisyphus/plans/{feature}.md` is the execution-state copy and may contain checked tasks or progress notes.',
      '',
      '## Notes',
      '',
      '- This command produces a development plan, not a design document.',
      '  Design work should already be complete before planning begins.',
      '- If design docs are missing, suggest running `/openflow-feature` first.',
      '- Plans are living documents during implementation. After saving the initial',
      '  version, the user or execution engine may update tasks as work progresses.',
    ].join('\n'),
  }
}
