import type { SkillInfo } from './types.js'

export function getWritingPlanSkill(): SkillInfo {
  return {
    name: 'openflow-writing-plan',
    description: 'Manual command reference for /openflow-writing-plan. Use only when the user explicitly requests /openflow-writing-plan or an implementation/development plan; never invoke from stuck /openflow-feature, brainstorm, or ULW flow. It prepares plan-writing context, then writes a structured plan to docs/changes/*/plan.md (and .sisyphus/plans/{feature}.md if OMO is present). When OMO is detected, execution routes to Prometheus; otherwise it routes to the OpenCode plan agent.',
    content: [
      '# OpenFlow Writing-Plan Command Reference',
      '',
      '## Overview',
      '',
      'This skill guides the production of a parser-compatible development plan for a feature.',
      'The primary artifact is saved to the change workspace (`docs/changes/YYYY-MM-DD-{feature}/plan.md`).',
      'If oh-my-openagent (OMO) is present, an identical initial copy is saved to `.sisyphus/plans/{feature}.md`.',
      "OpenFlow's plan enhancer may inject TDD guidance when configured.",
      '',
      '## Agent Target',
      '',
      '- **OMO detected** → Prometheus (interview, clearance, and execution)',
      '- **Non-OMO** → OpenCode native `plan` agent',
      '',
      'Agent selection is program-enforced. OpenFlow prepares the design context and constraints; the target agent owns the planning conversation.',
      '',
      '## Invocation Boundary',
      '',
      'Use this skill only when the user explicitly requests `/openflow-writing-plan <feature>` or asks for an implementation/development plan.',
      'Do NOT invoke this skill merely because `/openflow-feature` is active, stuck, incomplete, or has just generated design documents.',
      'Do NOT invoke this skill from brainstorm, ULW/ultrawork, or continuation flow unless the user explicitly asked for plan generation.',
      'When feature design is stuck, continue feature clarification or create/update only `design.md` and `behavior.md`; do not create `plan.md` or `.sisyphus/plans/*.md`.',
      'If a plan is the likely next step, suggest the explicit command and stop: `/openflow-writing-plan <feature>`.',
      '',
      '## Public Entry',
      '',
      'Start with:',
      '',
      '`/openflow-writing-plan <feature>`',
      '',
      '## Required Workflow',
      '',
      'Follow these steps in order. Do not skip or reorder them.',
      '',
      '### Step 1: Scope Check',
      '',
      'Before writing any plan, confirm the design boundary is clear:',
      '- Verify that design documents exist for the feature.',
      '- If design docs are missing, suggest running `/openflow-feature` first and STOP.',
      '- If requirements or design context are unclear, **stop and ask clarifying questions**. Do NOT generate a plan with DECISION-NEEDED placeholders.',
      '- When Prometheus is the target agent, let Prometheus perform its own interview and clearance checks. OpenFlow only supplies the design context packet.',
      '',
      '### Step 2: File Structure',
      '',
      'Identify and verify the expected output files (paths come from configuration, not hardcoded values):',
      '- Primary plan: `{config.paths.changes}/YYYY-MM-DD-{feature}/plan.md` (default: `docs/changes/...`)',
      '- OMO execution copy: `{config.paths.plans}/{feature}.md` (default: `.sisyphus/plans/...`)',
      '- Ensure parent directories exist before writing.',
      '- If either file already exists, tell the user and ask whether to overwrite or keep it. Do NOT silently overwrite.',
      '',
      '### Step 3: Plan Document Header',
      '',
      'Every plan MUST start with:',
      '',
      '```markdown',
      '# Plan: {feature}',
      '',
      '## Overview',
      'Brief description of what this feature accomplishes.',
      '',
      '## Design Context',
      'Reference to the design workspace and relevant constraints.',
      '',
      '## Execution Strategy',
      '',
      '### Parallel Execution Waves',
      'Wave 1: Tasks with no dependencies',
      'Wave 2: Tasks depending on Wave 1 results',
      '',
      '### Dependency Matrix',
      '| Task | Blocked By | Blocks |',
      '',
      '## Tasks',
      '- [ ] 1. Task name (Agent: quick | Blocks: [...] | Blocked By: [...])',
      '- [ ] 2. Another task',
      '```',
      '',
      '### Step 4: Task Structure',
      '',
      'The `## Tasks` section is critical. Every line must be a checkbox item (`- [ ] ...`) or a numbered item (`1. ...`) with a clear title.',
      '',
      '**Task Decomposition Rules:**',
      '- Group independent tasks into execution waves. Same-wave tasks are candidates for parallel execution.',
      '- Each task should be an independently deliverable work package with a clear boundary.',
      '- A single task may cover a few closely related files in the same module.',
      '- Do NOT mechanically create one task per file. Prefer cohesive work packages.',
      '- Limit same-wave concurrency: default max 3–4 tasks per wave unless justified.',
      '- Every task must include: Agent Profile (recommended category + skills), Parallelization status, Acceptance Criteria.',
      '- Include a Dependency Matrix: `| Task | Blocked By | Blocks |`.',
      '- After writing the plan, estimate total execution units (tasks × sub-items). If exceeded 20 units or same-wave > 4 tasks, merge smaller tasks or increase wave count.',
      '',
      'The plan must follow this structure:',
      '',
      '```markdown',
      '# Plan: {feature}',
      '',
      '## Overview',
      'Brief description of what this feature accomplishes.',
      '',
      '## Design Context',
      'Reference to the design workspace (e.g., `docs/changes/YYYY-MM-DD-{feature}/`).',
      '',
      '## Execution Strategy',
      '',
      '### Parallel Execution Waves',
      'Wave 1: Tasks with no dependencies',
      'Wave 2: Tasks depending on Wave 1 results',
      '',
      '### Dependency Matrix',
      '| Task | Blocked By | Blocks |',
      '',
      '## Tasks',
      '- [ ] 1. Task name (Agent: quick | Blocks: [...] | Blocked By: [...])',
      '- [ ] 2. Another task',
      '```',
      '',
      'The parser ignores any line that does not match these formats.',
      '',
      '### Step 5: No Placeholders',
      '',
      'Every task must be concrete and executable:',
      '- **No TBD, TODO, or "implement later"** in any task.',
      '- Every task specifies exact file paths to create or modify.',
      '- Every task includes a runnable verification command and expected output.',
      '- If a task spans more than 3–4 closely related files, split it.',
      '',
      '### Step 6: Remember',
      '',
      'Preserve design constraints and acceptance criteria from the design packet in every relevant task:',
      '- Carry forward severity-tagged constraints (e.g., `[HIGH / security]`) into task instructions.',
      '- Ensure acceptance criteria are reflected in task acceptance criteria or verification steps.',
      '- Do not silently drop constraints that were established during feature design.',
      '',
      '### Step 7: Self-Review',
      '',
      'Before finalizing, run this lightweight self-check against the plan:',
      '',
      '- **No placeholders**: Every task has a specific file path, not "somewhere in src/".',
      '- **Concrete verification**: Every task names a real command (e.g., `npm test -- path/to/test`, `npx tsc --noEmit`).',
      '- **Bounded complexity**: No single task describes an unreasonable amount of work. If a task spans more than 3–4 closely related files, split it.',
      '- **Task count**: Total tasks should be proportional to feature size: small features 3–5 tasks, medium 6–9, large 10–15.',
      '- **Parser-compatible**: The `## Tasks` section uses checkbox or numbered items exclusively.',
      '- **Quality gate present**: After implementation is complete, invoke the openflow-quality-gate skill. Do not claim completion until the quality gate reports readiness.',
      '',
      '### Step 8: Execution Handoff',
      '',
      'After the plan file is written, **stop**. Do not execute the plan.',
      'Do not create or suggest an `executing-plans` command.',
      'Do not invoke OMO, Prometheus, or any execution agent.',
      'Do not add OpenCode task blocks, start-work commands, or manual harden/verify commands.',
      '',
      'The user will provide the plan document to their execution environment:',
      '- If **Prometheus** is the target: hand off to Prometheus for interview, clearance, and execution.',
      '- If **plan** agent is the target: hand off to OpenCode native plan agent for execution.',
      '',
      'Your role ends when the file is saved.',
      '',
      '## Quality Gate Instruction',
      '',
      'The final implementation/QA task must instruct the executor to invoke the',
      '`openflow-quality-gate` skill after all code changes are complete.',
      '',
      'Use this wording:',
      '',
      '`After implementation is complete, invoke the openflow-quality-gate skill. The skill decides whether harden is required and performs evidence-aware verify. Do not claim completion until the quality gate reports readiness.`',
      '',
      'Do NOT tell the user to manually run `/openflow-harden` or `/openflow-verify`.',
      '',
      '## OMO / Prometheus Compatibility',
      '',
      '- This skill does NOT replace or disable any OMO/Prometheus built-in capabilities.',
      '  Prometheus exploration, brainstorming, and task planning features remain fully available.',
  '- When invoked inside a Prometheus session, use this skill to produce the plan artifact,',
  '  then let Prometheus continue its normal workflow (plan selection, execution, review).',
  '- The dual-save ensures Prometheus can find the plan in `.sisyphus/plans/` without',
  '  needing to look into `docs/changes/`.',
  '- The two copies must be identical at initial save time — this is one plan, saved to two locations.',
  '  After execution starts, `.sisyphus/plans/{feature}.md` becomes the execution-state copy, may diverge, and may contain checked tasks or progress notes.',
  '- **Prometheus Precedence**: If any instruction in this skill conflicts with Prometheus',
  '  behavior (e.g., interview mode, clearance checks, QA scenarios), Prometheus wins.',
  '  OpenFlow supplies the design context; Prometheus owns the planning conversation.',
  '',
  '## Notes',
  '',
  '- This command produces a development plan, not a design document.',
  '  Design work should already be complete before planning begins.',
  '- If design docs are missing, suggest running `/openflow-feature` first.',
  '- Plans are living documents during implementation. After saving the initial',
  '  version, the user or execution engine may update tasks as work progresses.',
  '- Output paths come from OpenFlow configuration; `docs/changes/` and `.sisyphus/plans/`',
  '  are defaults, not hardcoded requirements.',
    ].join('\n'),
  }
}
