import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import type { AcceptanceState, PendingDocUpdate, DevelopmentPhase } from '../types.js'
import { getAcceptanceStatePath } from '../config.js'
import { logger } from './logger.js'

const HEADER = `# OpenFlow Acceptance State

> Auto-generated by OpenFlow. Do not edit manually.

`

function formatTimestamp(): string {
  return new Date().toISOString()
}

function parseStateFile(content: string): AcceptanceState | null {
  const lines = content.split('\n')
  const result: Partial<AcceptanceState> = {
    pendingDocUpdates: []
  }
  
  let inPendingUpdates = false
  
  for (const line of lines) {
    const trimmed = line.trim()
    
    if (trimmed.startsWith('feature:')) {
      result.feature = trimmed.replace('feature:', '').trim()
      inPendingUpdates = false
    } else if (trimmed.startsWith('phase:')) {
      result.phase = trimmed.replace('phase:', '').trim() as DevelopmentPhase
      inPendingUpdates = false
    } else if (trimmed.startsWith('phaseStartedAt:')) {
      result.phaseStartedAt = trimmed.replace('phaseStartedAt:', '').trim()
      inPendingUpdates = false
    } else if (trimmed.startsWith('implementationEndedAt:')) {
      result.implementationEndedAt = trimmed.replace('implementationEndedAt:', '').trim()
      inPendingUpdates = false
    } else if (trimmed === '## Pending Document Updates') {
      inPendingUpdates = true
    } else if (inPendingUpdates && trimmed.startsWith('- `')) {
      const match = trimmed.match(/- `([^`]+)` \(([^)]+)\)(?: - (.+))?/)
      if (match && match[1] && match[2]) {
        result.pendingDocUpdates = result.pendingDocUpdates || []
        const update: PendingDocUpdate = {
          file: match[1],
          timestamp: match[2]
        }
        if (match[3]) {
          update.reason = match[3]
        }
        result.pendingDocUpdates.push(update)
      }
    }
  }
  
  if (!result.feature || !result.phase) {
    return null
  }
  
  return {
    feature: result.feature,
    phase: result.phase,
    phaseStartedAt: result.phaseStartedAt || formatTimestamp(),
    pendingDocUpdates: result.pendingDocUpdates || [],
    ...(result.implementationEndedAt ? { implementationEndedAt: result.implementationEndedAt } : {})
  }
}

function serializeState(state: AcceptanceState): string {
  const lines = [HEADER]
  
  lines.push('## Current State')
  lines.push('')
  lines.push(`feature: ${state.feature}`)
  lines.push(`phase: ${state.phase}`)
  lines.push(`phaseStartedAt: ${state.phaseStartedAt}`)
  if (state.implementationEndedAt) {
    lines.push(`implementationEndedAt: ${state.implementationEndedAt}`)
  }
  lines.push('')
  
  lines.push('## Pending Document Updates')
  lines.push('')
  if (state.pendingDocUpdates.length > 0) {
    for (const update of state.pendingDocUpdates) {
      const reason = update.reason ? ` - ${update.reason}` : ''
      lines.push(`- \`${update.file}\` (${update.timestamp})${reason}`)
    }
  } else {
    lines.push('No pending updates.')
  }
  
  return lines.join('\n')
}

export async function loadAcceptanceState(projectDir: string): Promise<AcceptanceState | null> {
  const statePath = getAcceptanceStatePath(projectDir)
  
  try {
    const content = await fs.readFile(statePath, 'utf-8')
    return parseStateFile(content)
  } catch {
    return null
  }
}

export async function saveAcceptanceState(projectDir: string, state: AcceptanceState): Promise<void> {
  const statePath = getAcceptanceStatePath(projectDir)
  const stateDir = path.dirname(statePath)
  
  await fs.mkdir(stateDir, { recursive: true })
  
  const content = serializeState(state)
  await fs.writeFile(statePath, content, 'utf-8')
  
  logger.debug('Saved acceptance state', { feature: state.feature, phase: state.phase })
}

export async function clearAcceptanceState(projectDir: string): Promise<void> {
  const statePath = getAcceptanceStatePath(projectDir)
  
  try {
    await fs.unlink(statePath)
    logger.debug('Cleared acceptance state')
  } catch {
    // File doesn't exist, ignore
  }
}

export async function enterAcceptancePhase(
  projectDir: string,
  feature: string
): Promise<AcceptanceState> {
  const existingState = await loadAcceptanceState(projectDir)
  
  if (existingState && existingState.feature === feature) {
    return existingState
  }
  
  const newState: AcceptanceState = {
    feature,
    phase: 'acceptance',
    phaseStartedAt: formatTimestamp(),
    pendingDocUpdates: []
  }
  
  await saveAcceptanceState(projectDir, newState)
  logger.info('Entered acceptance phase', { feature })
  
  return newState
}

export async function addPendingDocUpdate(
  projectDir: string,
  update: PendingDocUpdate
): Promise<void> {
  const state = await loadAcceptanceState(projectDir)
  
  if (!state) {
    logger.warn('Cannot add pending doc update: no active acceptance state')
    return
  }
  
  state.pendingDocUpdates.push(update)
  await saveAcceptanceState(projectDir, state)
}

export async function markImplementationComplete(projectDir: string): Promise<void> {
  const state = await loadAcceptanceState(projectDir)
  
  if (state) {
    state.implementationEndedAt = formatTimestamp()
    await saveAcceptanceState(projectDir, state)
  }
}
