import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import type { AcceptanceState, PendingDocUpdate, DevelopmentPhase, VerificationFailureCategory, CurrentPromotionSuggestion } from '../types.js'
import { getAcceptanceStatePath } from '../config.js'
import { logger } from './logger.js'

const HEADER = `# OpenFlow Acceptance State

> Auto-generated by OpenFlow. Do not edit manually.

`

const PENDING_UPDATES_HEADER = '## Pending Document Updates'

const FIELD_PREFIXES = {
  feature: 'feature:',
  phase: 'phase:',
  phaseStartedAt: 'phaseStartedAt:',
  sessionID: 'sessionID:',
  implementationEndedAt: 'implementationEndedAt:',
  verificationPromptedAt: 'verificationPromptedAt:',
  verificationCompletedAt: 'verificationCompletedAt:',
  verificationFailureCategory: 'verificationFailureCategory:',
  waitingForDocUpdateConfirm: 'waitingForDocUpdateConfirm:',
  lastChangedFile: 'lastChangedFile:',
  promotionApplied: 'promotionApplied:',
  promotionDecidedAt: 'promotionDecidedAt:',
  promotionAppliedAt: 'promotionAppliedAt:',
} as const

const PROMOTION_SUGGESTIONS_HEADER = '## Current Promotion Suggestions'

function formatTimestamp(): string {
  return new Date().toISOString()
}

function parseStateFile(content: string): AcceptanceState | null {
  const lines = content.split('\n')
  const result: Partial<AcceptanceState> = {
    pendingDocUpdates: []
  }
  
  let inPendingUpdates = false
  
  for (const line of lines) {
    const trimmed = line.trim()
    
    if (trimmed.startsWith(FIELD_PREFIXES.feature)) {
      result.feature = extractFieldValue(trimmed, FIELD_PREFIXES.feature)
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.phase)) {
      result.phase = extractFieldValue(trimmed, FIELD_PREFIXES.phase) as DevelopmentPhase
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.phaseStartedAt)) {
      result.phaseStartedAt = extractFieldValue(trimmed, FIELD_PREFIXES.phaseStartedAt)
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.sessionID)) {
      result.sessionID = extractFieldValue(trimmed, FIELD_PREFIXES.sessionID)
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.implementationEndedAt)) {
      result.implementationEndedAt = extractFieldValue(trimmed, FIELD_PREFIXES.implementationEndedAt)
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.verificationPromptedAt)) {
      result.verificationPromptedAt = extractFieldValue(trimmed, FIELD_PREFIXES.verificationPromptedAt)
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.verificationCompletedAt)) {
      result.verificationCompletedAt = extractFieldValue(trimmed, FIELD_PREFIXES.verificationCompletedAt)
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.verificationFailureCategory)) {
      result.verificationFailureCategory = extractFieldValue(trimmed, FIELD_PREFIXES.verificationFailureCategory) as VerificationFailureCategory
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.waitingForDocUpdateConfirm)) {
      const value = extractFieldValue(trimmed, FIELD_PREFIXES.waitingForDocUpdateConfirm)
      result.waitingForDocUpdateConfirm = value === 'true'
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.lastChangedFile)) {
      result.lastChangedFile = extractFieldValue(trimmed, FIELD_PREFIXES.lastChangedFile)
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.promotionApplied)) {
      const value = extractFieldValue(trimmed, FIELD_PREFIXES.promotionApplied)
      result.promotionApplied = value === 'true'
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.promotionDecidedAt)) {
      result.promotionDecidedAt = extractFieldValue(trimmed, FIELD_PREFIXES.promotionDecidedAt)
      inPendingUpdates = false
    } else if (trimmed.startsWith(FIELD_PREFIXES.promotionAppliedAt)) {
      result.promotionAppliedAt = extractFieldValue(trimmed, FIELD_PREFIXES.promotionAppliedAt)
      inPendingUpdates = false
    } else if (trimmed === PENDING_UPDATES_HEADER) {
      inPendingUpdates = true
      result.promotionSuggestions = result.promotionSuggestions || []
    } else if (trimmed === PROMOTION_SUGGESTIONS_HEADER) {
      inPendingUpdates = false
      result.promotionSuggestions = result.promotionSuggestions || []
    } else if (inPendingUpdates && trimmed.startsWith('- `')) {
      const match = trimmed.match(/- `([^`]+)` \(([^)]+)\)(?: - (.+))?/)
      if (match && match[1] && match[2]) {
        result.pendingDocUpdates = result.pendingDocUpdates || []
        const update: PendingDocUpdate = {
          file: match[1],
          timestamp: match[2]
        }
        if (match[3]) {
          update.reason = match[3]
        }
        result.pendingDocUpdates.push(update)
      }
    } else if (trimmed.startsWith('- [') && result.promotionSuggestions) {
      const match = trimmed.match(/- \[([^\]]+)\] ([^:]+): (.+)$/)
      if (match && match[1] && match[2] && match[3]) {
        const type = match[1].trim()
        if (type === 'ADD' || type === 'UPDATE' || type === 'REMOVE') {
          const suggestion: CurrentPromotionSuggestion = {
            type,
            targetArea: (match[2].trim() === 'requirements' ? 'requirements' : 'design'),
            targetPath: match[3].trim(),
            reason: 'Recovered from state file',
          }
          result.promotionSuggestions.push(suggestion)
        }
      }
    }
  }
  
  if (!result.feature || !result.phase) {
    return null
  }
  
  const state: AcceptanceState = {
    feature: result.feature,
    phase: result.phase,
    phaseStartedAt: result.phaseStartedAt || formatTimestamp(),
    pendingDocUpdates: result.pendingDocUpdates || []
  }

  if (result.sessionID) {
    state.sessionID = result.sessionID
  }
  
  if (result.implementationEndedAt) {
    state.implementationEndedAt = result.implementationEndedAt
  }
  if (result.verificationPromptedAt) {
    state.verificationPromptedAt = result.verificationPromptedAt
  }
  if (result.verificationCompletedAt) {
    state.verificationCompletedAt = result.verificationCompletedAt
  }
  if (result.verificationFailureCategory) {
    state.verificationFailureCategory = result.verificationFailureCategory
  }
  if (result.waitingForDocUpdateConfirm !== undefined) {
    state.waitingForDocUpdateConfirm = result.waitingForDocUpdateConfirm
  }
  if (result.lastChangedFile) {
    state.lastChangedFile = result.lastChangedFile
  }
  if (result.promotionSuggestions && result.promotionSuggestions.length > 0) {
    state.promotionSuggestions = result.promotionSuggestions
  }
  if (result.promotionApplied !== undefined) {
    state.promotionApplied = result.promotionApplied
  }
  if (result.promotionDecidedAt) {
    state.promotionDecidedAt = result.promotionDecidedAt
  }
  if (result.promotionAppliedAt) {
    state.promotionAppliedAt = result.promotionAppliedAt
  }
  
  return state
}

function serializeState(state: AcceptanceState): string {
  const lines = [HEADER]
  
  lines.push('## Current State')
  lines.push('')
  lines.push(`${FIELD_PREFIXES.feature} ${state.feature}`)
  lines.push(`${FIELD_PREFIXES.phase} ${state.phase}`)
  lines.push(`${FIELD_PREFIXES.phaseStartedAt} ${state.phaseStartedAt}`)
  pushOptionalLine(lines, FIELD_PREFIXES.sessionID, state.sessionID)
  pushOptionalLine(lines, FIELD_PREFIXES.implementationEndedAt, state.implementationEndedAt)
  pushOptionalLine(lines, FIELD_PREFIXES.verificationPromptedAt, state.verificationPromptedAt)
  pushOptionalLine(lines, FIELD_PREFIXES.verificationCompletedAt, state.verificationCompletedAt)
  pushOptionalLine(lines, FIELD_PREFIXES.verificationFailureCategory, state.verificationFailureCategory)
  if (state.waitingForDocUpdateConfirm !== undefined) {
    lines.push(`${FIELD_PREFIXES.waitingForDocUpdateConfirm} ${state.waitingForDocUpdateConfirm}`)
  }
  pushOptionalLine(lines, FIELD_PREFIXES.lastChangedFile, state.lastChangedFile)
  if (state.promotionApplied !== undefined) {
    lines.push(`${FIELD_PREFIXES.promotionApplied} ${state.promotionApplied}`)
  }
  pushOptionalLine(lines, FIELD_PREFIXES.promotionDecidedAt, state.promotionDecidedAt)
  pushOptionalLine(lines, FIELD_PREFIXES.promotionAppliedAt, state.promotionAppliedAt)
  lines.push('')
  
  lines.push(PENDING_UPDATES_HEADER)
  lines.push('')
  if (state.pendingDocUpdates.length > 0) {
    for (const update of state.pendingDocUpdates) {
      const reason = update.reason ? ` - ${update.reason}` : ''
      lines.push(`- \`${update.file}\` (${update.timestamp})${reason}`)
    }
  } else {
    lines.push('No pending updates.')
  }

  lines.push('')
  lines.push(PROMOTION_SUGGESTIONS_HEADER)
  lines.push('')
  if (state.promotionSuggestions && state.promotionSuggestions.length > 0) {
    for (const suggestion of state.promotionSuggestions) {
      lines.push(`- [${suggestion.type}] ${suggestion.targetArea}: ${suggestion.targetPath}`)
    }
  } else {
    lines.push('No promotion suggestions.')
  }
  
  return lines.join('\n')
}

function extractFieldValue(line: string, prefix: string): string {
  return line.slice(prefix.length).trim()
}

function pushOptionalLine(lines: string[], key: string, value?: string): void {
  if (value) {
    lines.push(`${key} ${value}`)
  }
}

export async function loadAcceptanceState(projectDir: string): Promise<AcceptanceState | null> {
  const statePath = getAcceptanceStatePath(projectDir)
  
  try {
    const content = await fs.readFile(statePath, 'utf-8')
    return parseStateFile(content)
  } catch {
    return null
  }
}

export async function saveAcceptanceState(projectDir: string, state: AcceptanceState): Promise<void> {
  const statePath = getAcceptanceStatePath(projectDir)
  const stateDir = path.dirname(statePath)
  
  await fs.mkdir(stateDir, { recursive: true })
  
  const content = serializeState(state)
  await fs.writeFile(statePath, content, 'utf-8')
  
  logger.debug('Saved acceptance state', { feature: state.feature, phase: state.phase })
}

export async function clearAcceptanceState(projectDir: string): Promise<void> {
  const statePath = getAcceptanceStatePath(projectDir)
  
  try {
    await fs.unlink(statePath)
    logger.debug('Cleared acceptance state')
  } catch {
    // File doesn't exist, ignore
  }
}

export async function enterAcceptancePhase(
  projectDir: string,
  feature: string,
  sessionID?: string
): Promise<AcceptanceState> {
  const existingState = await loadAcceptanceState(projectDir)
  
  if (existingState && existingState.feature === feature) {
    return existingState
  }
  
  const newState: AcceptanceState = {
    feature,
    phase: 'acceptance',
    phaseStartedAt: formatTimestamp(),
    pendingDocUpdates: []
  }

  newState.implementationEndedAt = newState.phaseStartedAt

  if (sessionID) {
    newState.sessionID = sessionID
  }
  
  await saveAcceptanceState(projectDir, newState)
  logger.info('Entered acceptance phase', { feature })
  
  return newState
}

export async function addPendingDocUpdate(
  projectDir: string,
  update: PendingDocUpdate
): Promise<void> {
  const state = await loadAcceptanceState(projectDir)
  
  if (!state) {
    logger.warn('Cannot add pending doc update: no active acceptance state')
    return
  }
  
  state.pendingDocUpdates.push(update)
  state.lastChangedFile = update.file
  await saveAcceptanceState(projectDir, state)
}

export async function setWaitingForDocUpdateConfirm(
  projectDir: string,
  filePath: string
): Promise<void> {
  const state = await loadAcceptanceState(projectDir)
  
  if (!state) {
    logger.warn('Cannot set waiting state: no active acceptance state')
    return
  }
  
  state.waitingForDocUpdateConfirm = true
  state.lastChangedFile = filePath
  await saveAcceptanceState(projectDir, state)
}

export async function clearWaitingForDocUpdateConfirm(projectDir: string): Promise<void> {
  const state = await loadAcceptanceState(projectDir)
  
  if (state) {
    state.waitingForDocUpdateConfirm = false
    delete state.lastChangedFile
    await saveAcceptanceState(projectDir, state)
  }
}

export async function markImplementationComplete(projectDir: string): Promise<void> {
  const state = await loadAcceptanceState(projectDir)
  
  if (state) {
    state.implementationEndedAt = formatTimestamp()
    await saveAcceptanceState(projectDir, state)
  }
}
